### ISSUE TITLE
Long file names don't wrap in table of files.

### ISSUE THREAD

**Issue by rkillick** [retostauffer/ojstransition#2]
This means that the formatting is off and we can't access the blue triangles on the right.  See 4497 for (the only) example.

I'm happy for the solution to be that we manually change the filenames (which we can easily do) to avoid the issue, but I wanted to flag it in case you wanted to handle it a different way.

**Comment by retostauffer** [comment]
@Falk358 and I spotted this as well. We'll discuss this in our next tech meeting. Not easy to fix as embedded in HTML tables and the file names cannot be wrapped. We could hide the overflow which means that one can only see part of the file names. Simplest would be to rename the files manually in these situations where authors chose a somewhat bulky name. 

We'll get back to you.

**Comment by rkillick** [comment]
Agree that the fix isn't easy.  Editors renaming files is fine as a solution as it won't happen very often and is quick and easy to do.

The other option would be to have a max filename length when the authors upload as they are given the opportunity to rename files.  If a maximum is in place then the "ok" at that stage would throw an error to the user.

**Comment by retostauffer** [comment]
Perfect; thanks. Limiting the maximum length is not that easy and would require multiple bugfixes here and there and we somewhat 'misuse' this field. Thus we would need to maintain this fix forever. I think we can live with renaming for now; if this gets out of hand we may think  of somehow limiting the file name on the browser side (with some jquery magic).

**Comment by rkillick** [comment]
Agreed that we can live with a manual fix.
