### ISSUE TITLE
Pre-screening response email outdated?

### ISSUE THREAD

**Issue by davidruegamer** [retostauffer/ojstransition#3]
I received the following Editor Decision email after the pre-screening stage:

> [...] Once you have made the requested changes, please upload your revised materials as a single compressed file (e.g. "JSSxxx_prescreened.zip") via the "Upload Author Version" link on your submission's review page: https://www.jstatsoft.org/author/submissionReview/[xxx]. 

Unfortunately, neither is the link working (at least for me), nor am I sure where exactly to upload the zip file. As "Others" in the revision menu?

![JSS_revision](https://user-images.githubusercontent.com/11161637/138438606-1caec369-d00f-4021-9282-30152cceaab4.png)

Many Thanks,
David

**Comment by retostauffer** [comment]
Dear David (@davidruegamer)

First things first: Uploading it as 'Others' as you did is perfect.

This email is composed manually as it contains submission-specific prescreening comments. The broken URL is a copy&past issue, sorry for that. I will get in touch with our editorial office to improve this message for future use. Thank you very much for reporting, this helps us a lot to fine-tune everything.

In case you have any questions do not hesitate to reach out to me again.

All best,
Reto

**Comment by davidruegamer** [comment]
Many thanks for the quick reply @retostauffer !

Another issue I just came across when uploading the zip file:

On the submission page it says

> Information for authors
When you have uploaded Revisions for all required files above (including your point-to-point response), you need to inform the editors that your revision is complete. To do so click the Add discussion button below, using the subject "Resubmission" and adding all involved section editors and journal editors (if any) as participants.

But if I click on "Add discussion" there is only a blank window that pops up. 

![Screenshot from 2021-10-22 13-04-16](https://user-images.githubusercontent.com/11161637/138443927-331fe9d1-c21c-4eb6-9084-7cfe401f958f.png)

After reloading the page, the discussion seems to be added, but there is no name or message attached to it:

![Screenshot from 2021-10-22 13-04-26](https://user-images.githubusercontent.com/11161637/138443957-a29c53b5-72b6-4019-8c95-fe2545c21343.png)

It is also not possible to edit the discussion using the "Edit" button, which again yields a blank pop up:

![Screenshot from 2021-10-22 13-04-34](https://user-images.githubusercontent.com/11161637/138444038-5748d676-3d6b-4373-9393-d0949b88434f.png)

Is this how it is supposed to be? Or did I do something wrong? 
Let me know if I should copy this over to another Github issue.

Best,
David

**Comment by retostauffer** [comment]
Hy @davidruegamer 

The form needs 3-5 seconds to load after you click on "Add Discussion", but it should show up. If you cancel this process it will add the empty discussion you can see above. 

As your screenshot shows you can "Edit" or "Delete" your discussion (and start a new one); just tested it for your specific case/user and it should work. May I ask you to try that once again - and give the system a few seconds to load the form properly? What you should see is:

![discussion](https://user-images.githubusercontent.com/13628564/138451509-1bff9c47-013e-483e-8261-0c2ea8c62f6d.png)

Thanks a lot and sorry for the inconvenience,
Reto

**Comment by davidruegamer** [comment]
Hi Reto,

many thanks again for the prompt response. It actually seems like I was just too impatient with your system. After waiting a few seconds, I was able to add Editors/Admins, a subject and a message. 👍🏻  

Would it make sense to add a note of patience for the impatient user like me? Because apparently I had enough time to take a screenshot and then close the pop-up window again without noticing any changes.

Best,
David

**Comment by retostauffer** [comment]
I have added a note that this will take few seconds :). Thanks for your report, very much appreciated.
