### ISSUE TITLE
RSS feed appears to be broken

### ISSUE THREAD

**Issue by jthaman** [retostauffer/ojstransition#5]
I have no way of telling if this is related to the transition, but I cannot receive updates from the site RSS feed anymore. The feed I had been using is:

https://www.jstatsoft.org/notification/notificationFeed/rss/68332083656027ec86d149

I hope a new feed is available.

**Comment by retostauffer** [comment]
Dear @jthaman 

The feed is still available but the end-point has changed in OJS3. We have an entry point on:

* <https://www.jstatsoft.org/rss> (forwards to <https://www.jstatsoft.org/gateway/plugin/WebFeedGatewayPlugin/rss2>)

**Comment by jthaman** [comment]
Yay! That works!
