### ISSUE TITLE
“Last activity recorded on invalid date”

### ISSUE THREAD

**Issue by jmniehaus** [retostauffer/ojstransition#6]
A recent submission has a red submission tag in the dashboard, and says its last activity was on an invalid date. It is unclear what this means, and whether any action is required on part of the submitter in order to ensure that that the submission is received. Submission number 4669.

**Comment by retostauffer** [comment]
Dear @jmniehaus 

First of all I have to apologize not responding much earlier; I have been out of office over the past few days. Thanks for reporting the problem, nothing we have heard so far and I was not able to reproduce it/find any indication for it.

To me everything seems to be fine; the submission is currently discussed (pre-screening stage).

**Comment by retostauffer** [comment]
Closing issue
