### ISSUE TITLE
Not listed in PubMed

### ISSUE THREAD

**Issue by stdepi** [retostauffer/ojstransition#7]
Jones JH, demogR: A Package for the Construction and Analysis of Age-structured Demographic Models in R, 2007

Doesn't appear in PubMed. Perhaps they don't list JSS articles that far back?

**Comment by zeileis** [comment]
We do not control the indexing of PubMed. I think PubMed themselves don't do any indexing of JSS at all. The 80 or so JSS papers that appear in PubMed were probably submitted by individuals and then incorporated.

Thus, if it is important to you to have that 2007 paper in PubMed, I would probably submit it and see whether they decide to include it.
