### ISSUE TITLE
Cannot start a new submission

### ISSUE THREAD

**Issue by talgalili** [retostauffer/ojstransition#8]
I try to login through:
https://www.jstatsoft.org/login?source=%2Fsubmissions
It just redirects me to the login page.

I do it in incognito window and get to:
https://www.jstatsoft.org/submissions

I start a new submission, fill in the details in "start" at:
https://www.jstatsoft.org/submission/wizard
Press "save and continue"
And if the notes to the editor is empty - then no problem. But if I put text in it - I just get logged out.

When I'm moved to the "upload submission" page - it is empty:
<img width="1204" alt="image" src="https://github.com/retostauffer/ojstransition/assets/976006/83fb749f-2a93-4f22-9f9c-9714c0c07354">

If I log out - and un mark the "keep me logged in" - it seems to now works fine.

Very odd...

**Comment by talgalili** [comment]
After playing with this some more, it seems to be some issue with cookies or something like that. It seems that my user keeps loging out within less than a minute.

**Comment by retostauffer** [comment]
Thanks for your additional tests @talgalili 

I try to have a look at it this week; May I ask which OS and browser combination you use? Given the screenshot my guess would be ... chrome?

I apologize for the inconvenience.

**Comment by talgalili** [comment]
Thanks.

Mac + Chrome.

Here are the versions:

```
talgalili@talgalili-mbp ~ %
talgalili@talgalili-mbp ~ % sw_vers

ProductName:		macOS
ProductVersion:		13.4.1
ProductVersionExtra:	(c)
BuildVersion:		22F770820d
talgalili@talgalili-mbp ~ % mdls -name kMDItemVersion /Applications/Google\ Chrome.app

kMDItemVersion = "114.0.5735.198"
```

**Comment by markvanderloo** [comment]
I also cannot login from the https://www.jstatsoft.org/login page.

linux (Ubuntu 20.04) + Chromium, also not via private browser. I will try Tal's recipe.

**edit** I keep getting 'Invalid User or Password'. Doesn't matter if it is on an incognito tab or not, does not matter if I go to the login page or the submission page. Resetting the password also did not help.

**edit again** never mind: I tried to log in using my email address instead of my user name... It all works now.

**Comment by retostauffer** [comment]
Ups. Forgot to reply back in August.

We have tried to reproduce the issue but were not able to do so (not even with brave). @markvanderloo happy to hear logging in with your email address worked; technically this should not have worked as far as I am aware.

As we have not gotten any more requests regarding this problem I assume (hope) it was a temporary/random problem. Please come back to me if similar issues occur again.
